services:
  api:
    container_name: infierno-api-antelope
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # API interna escucha en 7860 => host 9100
    ports:
      - "9100:7860"

    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_GRPC_URL=http://qdrant:6334
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_GRPC_HOST=qdrant
      - QDRANT_GRPC_PORT=6334

      - COLLECTION_NAME=faces
      - THUMBS_DIR=/data/thumbs
      - SQLITE_DB=/state/ingestion.db

      - MODEL_NAME=buffalo_l
      - DET_SIZE=640,640
      - MAX_SIDE=1600
      - DOWNSCALE_TO=1280

      - TOP_K=10
      - SIM_THRESHOLD=0.0
      - HNSW_EF=256
      - TTA_SEARCH=1
      - QUANTIZATION=scalar

    depends_on:
      - qdrant

    volumes:
      - ./logs:/logs
      - ./state:/state
      - ./thumbs:/data/thumbs
      - ./models:/models
      - ${HOME}:/hosthome

    gpus: all

  qdrant:
    container_name: infierno-qdrant-antelope
    image: qdrant/qdrant:v1.9.1
    restart: unless-stopped

    ports:
      - "9101:6333"
      - "9102:6334"

    volumes:
      - ./qdrant_storage:/qdrant/storage
